<a href="https://colab.research.google.com/github/CarolinaOutoffice/NumPy/blob/main/desafio_telecom_x_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Desafio Telecom X

##Extracción


📘 DICCIONARIO DE DATOS

| Campo             | Descripción                                                                 |
|-------------------|------------------------------------------------------------------------------|
| customerID        | Número de identificación único de cada cliente                              |
| Churn             | Si el cliente dejó o no la empresa                                           |
| gender            | Género (masculino o femenino)                                                |
| SeniorCitizen     | Información sobre si un cliente tiene o no una edad igual o mayor a 65 años |
| Partner           | Si el cliente tiene o no una pareja                                          |
| Dependents        | Si el cliente tiene o no dependientes                                        |
| tenure            | Meses de contrato del cliente                                                |
| PhoneService      | Suscripción al servicio telefónico                                           |
| MultipleLines     | Suscripción a más de una línea telefónica                                    |
| InternetService   | Suscripción a un proveedor de internet                                       |
| OnlineSecurity    | Suscripción adicional de seguridad en línea                                  |
| OnlineBackup      | Suscripción adicional de respaldo en línea                                   |
| DeviceProtection  | Suscripción adicional de protección del dispositivo                          |
| TechSupport       | Suscripción adicional de soporte técnico, menor tiempo de espera             |
| StreamingTV       | Suscripción de televisión por cable                                          |
| StreamingMovies   | Suscripción de streaming de películas                                        |
| Contract          | Tipo de contrato                                                             |
| PaperlessBilling  | Si el cliente prefiere recibir la factura en línea                           |
| PaymentMethod     | Forma de pago                                                                |
| Charges.Monthly   | Total de todos los servicios del cliente por mes                             |
| Charges.Total     | Total gastado por el cliente                                                 |

In [12]:
#!pip install requests
import requests
import pandas as pd
import matplotlib.pyplot as plt

#url de la API
url='https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json'

#realizamos la solicitud GET
respuesta_api=requests.get(url)
data=respuesta_api.json()

In [13]:
df=pd.DataFrame(data)
print(df.head())

   customerID Churn                                           customer  \
0  0002-ORFBO    No  {'gender': 'Female', 'SeniorCitizen': 0, 'Part...
1  0003-MKNFE    No  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
2  0004-TLHLJ   Yes  {'gender': 'Male', 'SeniorCitizen': 0, 'Partne...
3  0011-IGKFF   Yes  {'gender': 'Male', 'SeniorCitizen': 1, 'Partne...
4  0013-EXCHZ   Yes  {'gender': 'Female', 'SeniorCitizen': 1, 'Part...

                                             phone  \
0   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
1  {'PhoneService': 'Yes', 'MultipleLines': 'Yes'}
2   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
3   {'PhoneService': 'Yes', 'MultipleLines': 'No'}
4   {'PhoneService': 'Yes', 'MultipleLines': 'No'}

                                            internet  \
0  {'InternetService': 'DSL', 'OnlineSecurity': '...
1  {'InternetService': 'DSL', 'OnlineSecurity': '...
2  {'InternetService': 'Fiber optic', 'OnlineSecu...
3  {'InternetService': 'Fiber optic', 'OnlineSecu...
4  {'InternetService': 'Fiber optic', 'OnlineSecu...

                                             account
0  {'Contract': 'One year', 'PaperlessBilling': '...
1  {'Contract': 'Month-to-month', 'PaperlessBilli...
2  {'Contract': 'Month-to-month', 'PaperlessBilli...
3  {'Contract': 'Month-to-month', 'PaperlessBilli...
4  {'Contract': 'Month-to-month', 'PaperlessBilli...

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

## Transformación

In [15]:
#Normalizamos
df_normalizado=pd.json_normalize(data)
print(df_normalizado.head())

   customerID Churn customer.gender  customer.SeniorCitizen customer.Partner  \
0  0002-ORFBO    No          Female                       0              Yes
1  0003-MKNFE    No            Male                       0               No
2  0004-TLHLJ   Yes            Male                       0               No
3  0011-IGKFF   Yes            Male                       1              Yes
4  0013-EXCHZ   Yes          Female                       1              Yes

  customer.Dependents  customer.tenure phone.PhoneService phone.MultipleLines  \
0                 Yes                9                Yes                  No
1                  No                9                Yes                 Yes
2                  No                4                Yes                  No
3                  No               13                Yes                  No
4                  No                3                Yes                  No

  internet.InternetService  ... internet.OnlineBackup  \
0                      DSL  ...                   Yes
1                      DSL  ...                    No
2              Fiber optic  ...                    No
3              Fiber optic  ...                   Yes
4              Fiber optic  ...                    No

  internet.DeviceProtection internet.TechSupport internet.StreamingTV  \
0                        No                  Yes                  Yes
1                        No                   No                   No
2                       Yes                   No                   No
3                       Yes                   No                  Yes
4                        No                  Yes                  Yes

  internet.StreamingMovies account.Contract account.PaperlessBilling  \
0                       No         One year                      Yes
1                      Yes   Month-to-month                       No
2                       No   Month-to-month                      Yes
3                      Yes   Month-to-month                      Yes
4                       No   Month-to-month                      Yes

  account.PaymentMethod account.Charges.Monthly  account.Charges.Total
0          Mailed check                    65.6                  593.3
1          Mailed check                    59.9                  542.4
2      Electronic check                    73.9                 280.85
3      Electronic check                    98.0                1237.85
4          Mailed check                    83.9                  267.4

[5 rows x 21 columns]

In [16]:
df_normalizado.info()
df_normalizado.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

###Revision general (analisis exploratorio)

In [17]:
#Verificar valores unicos
for columna in df_normalizado.columns:
  valores_unicos=df_normalizado[columna].nunique()
  print(f'La columna {columna} tiene {valores_unicos} valores unicos')
  if df_normalizado[columna].nunique() < 50:
    print(df_normalizado[columna].unique())
    print('-' * 50)

La columna customerID tiene 7267 valores unicos
La columna Churn tiene 3 valores unicos
['No' 'Yes' '']
--------------------------------------------------
La columna customer.gender tiene 2 valores unicos
['Female' 'Male']
--------------------------------------------------
La columna customer.SeniorCitizen tiene 2 valores unicos
[0 1]
--------------------------------------------------
La columna customer.Partner tiene 2 valores unicos
['Yes' 'No']
--------------------------------------------------
La columna customer.Dependents tiene 2 valores unicos
['Yes' 'No']
--------------------------------------------------
La columna customer.tenure tiene 73 valores unicos
La columna phone.PhoneService tiene 2 valores unicos
['Yes' 'No']
--------------------------------------------------
La columna phone.MultipleLines tiene 3 valores unicos
['No' 'Yes' 'No phone service']
--------------------------------------------------
La columna internet.InternetService tiene 3 valores unicos
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
La columna internet.OnlineSecurity tiene 3 valores unicos
['No' 'Yes' 'No internet service']
--------------------------------------------------
La columna internet.OnlineBackup tiene 3 valores unicos
['Yes' 'No' 'No internet service']
--------------------------------------------------
La columna internet.DeviceProtection tiene 3 valores unicos
['No' 'Yes' 'No internet service']
--------------------------------------------------
La columna internet.TechSupport tiene 3 valores unicos
['Yes' 'No' 'No internet service']
--------------------------------------------------
La columna internet.StreamingTV tiene 3 valores unicos
['Yes' 'No' 'No internet service']
--------------------------------------------------
La columna internet.StreamingMovies tiene 3 valores unicos
['No' 'Yes' 'No internet service']
--------------------------------------------------
La columna account.Contract tiene 3 valores unicos
['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
La columna account.PaperlessBilling tiene 2 valores unicos
['Yes' 'No']
--------------------------------------------------
La columna account.PaymentMethod tiene 4 valores unicos
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
La columna account.Charges.Monthly tiene 1585 valores unicos
La columna account.Charges.Total tiene 6531 valores unicos

In [18]:
#Vericar duplicados
duplicados=df_normalizado[columna].duplicated().sum()
print(f'La columna {columna} tiene {duplicados} duplicados')

La columna account.Charges.Total tiene 736 duplicados

In [19]:
#Verificar valores nulos
for columna in df_normalizado.columns:
  valores_nulos=df_normalizado[columna].isnull().sum()
  print(f'La columna {columna} tiene {valores_nulos} valores nulos')

La columna customerID tiene 0 valores nulos
La columna Churn tiene 0 valores nulos
La columna customer.gender tiene 0 valores nulos
La columna customer.SeniorCitizen tiene 0 valores nulos
La columna customer.Partner tiene 0 valores nulos
La columna customer.Dependents tiene 0 valores nulos
La columna customer.tenure tiene 0 valores nulos
La columna phone.PhoneService tiene 0 valores nulos
La columna phone.MultipleLines tiene 0 valores nulos
La columna internet.InternetService tiene 0 valores nulos
La columna internet.OnlineSecurity tiene 0 valores nulos
La columna internet.OnlineBackup tiene 0 valores nulos
La columna internet.DeviceProtection tiene 0 valores nulos
La columna internet.TechSupport tiene 0 valores nulos
La columna internet.StreamingTV tiene 0 valores nulos
La columna internet.StreamingMovies tiene 0 valores nulos
La columna account.Contract tiene 0 valores nulos
La columna account.PaperlessBilling tiene 0 valores nulos
La columna account.PaymentMethod tiene 0 valores nulos
La columna account.Charges.Monthly tiene 0 valores nulos
La columna account.Charges.Total tiene 0 valores nulos

In [20]:
#Verifica valores en blanco
en_blanco=df_normalizado.apply(lambda x: x.astype(str).str.strip()=='').sum()
print("\nValores en blanco o string vacios por columna")
print(en_blanco[en_blanco>0])

Valores en blanco o string vacios por columna
Churn                    224
account.Charges.Total     11
dtype: int64

In [21]:
#Cambiar tipo de datos a texto excepto customer.SeniorCitizen, account.Charges.Monthly, account.Charges.Total
excluir=['customer.SeniorCitizen', 'account.Charges.Monthly', 'account.Charges.Total', 'customer.Partner','customer.Dependents','phone.PhoneService','account.PaperlessBilling']
for columna in df_normalizado.columns:
  if columna not in excluir:
    df_normalizado[columna]=df_normalizado[columna].astype('string')

df_normalizado['customer.tenure']=df_normalizado['customer.tenure'].astype('int64')
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   string
 1   Churn                      7267 non-null   string
 2   customer.gender            7267 non-null   string
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   string
 9   internet.InternetService   7267 non-null   string
 10  internet.OnlineSecurity    7267 non-null   string
 11  internet.OnlineBackup      7267 non-null   string
 12  internet.DeviceProtection  7267 non-null   string
 13  internet.TechSupport       7267 non-null   string
 14  internet.StreamingTV       7267 non-null   string
 15  internet.StreamingMovies   7267 non-null   string
 16  account.Contract           7267 non-null   string
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   string
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(5), string(13)
memory usage: 1.2+ MB

In [22]:
# Revision de registros con account.Charges.Total vacio
criterio=df_normalizado['account.Charges.Total'].str.strip() == ''
df_normalizado[criterio]

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [23]:
# REGISTROS DONDE COLUMNA TENURE=0
criterio=df_normalizado['customer.tenure']==0
df_normalizado[criterio]

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
975,1371-DWPAZ,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,
1775,2520-SGTTA,No,Female,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,
1955,2775-SEFEE,No,Male,0,No,Yes,0,Yes,Yes,DSL,...,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,
2075,2923-ARZLG,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,
2232,3115-CZMZD,No,Male,0,No,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,
2308,3213-VVOLG,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,
2930,4075-WKNIU,No,Female,0,Yes,Yes,0,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,
3134,4367-NUYAO,No,Male,0,Yes,Yes,0,Yes,Yes,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,
3203,4472-LVYGI,No,Female,0,Yes,Yes,0,No,No phone service,DSL,...,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,
4169,5709-LVOEQ,No,Female,0,Yes,Yes,0,Yes,No,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,
5599,7644-OMVMY,No,Male,0,Yes,Yes,0,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,

In [24]:
# Modificar account.Charges.Total vacios a ceros y se pasa el mismo campo a tipo float
''' Debido a que los registros vacios de account.Charges.Total coinciden con los casos que tienen 0 meses facturados (customer.tenure) se decido modificar estos caso a valor 0.'''
df_normalizado.loc[df_normalizado['account.Charges.Total'].str.strip() == '', 'account.Charges.Total'] = '0'

df_normalizado['account.Charges.Total']=df_normalizado['account.Charges.Total'].astype('float')

In [25]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   string
 1   Churn                      7267 non-null   string
 2   customer.gender            7267 non-null   string
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   string
 9   internet.InternetService   7267 non-null   string
 10  internet.OnlineSecurity    7267 non-null   string
 11  internet.OnlineBackup      7267 non-null   string
 12  internet.DeviceProtection  7267 non-null   string
 13  internet.TechSupport       7267 non-null   string
 14  internet.StreamingTV       7267 non-null   string
 15  internet.StreamingMovies   7267 non-null   string
 16  account.Contract           7267 non-null   string
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   string
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   float64
dtypes: float64(2), int64(2), object(4), string(13)
memory usage: 1.2+ MB

In [26]:
# Datos Atipicos para columnas numericas
def detectar_datos_atipicos(df, columna, regla_m0=lambda x: x > 0):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    #filtro estadístico
    atipicos = df[(df[columna] < limite_inferior) | (df[columna] > limite_superior)]

    #filtro valor 0
    atipicos_0 = df[~df[columna].apply(regla_m0)]

    #Combina filtros
    resultado=pd.concat([atipicos, atipicos_0]).drop_duplicates()

    #Reportar
    print(f"📌 Outliers en '{columna}': {len(atipicos)+len(atipicos_0)} registros")
    print(f"  - Límite inferior: {limite_inferior:.2f}")
    print(f"  - Límite superior: {limite_superior:.2f}")

   # return resultado[[columna]];

# Datos atipicos para columnas categoricas (texto)
def detectar_datos_atipicos_texto(df, columna):
    resultado = df[
        df[columna].isna() |                                # detecta NaN
        (df[columna].apply(lambda x: isinstance(x, str) and x.strip() == ''))  # detecta strings vacíos o con espacios
    ]

    print(f"📌 Registros vacíos o inválidos en '{columna}': {len(resultado)} encontrados")
    #return resultado[[columna]]

In [37]:
df_normalizado['Churn'] = df_normalizado['Churn'].replace(['', None], 'NC').fillna('NC')

print("\nDespues de reemplazar, nan y '' en 'Churn':")
print(df_normalizado['Churn'].value_counts(dropna=False))
print("\nChequando vacios en  'Churn' despues de reemplazar:")
print(df_normalizado[df_normalizado['Churn'].str.strip() == '']['Churn'].count())
print("\nChequeando nulos en 'Churn' despues de reemplazar:")
print(df_normalizado['Churn'].isnull().sum())

Despues de reemplazar, nan y '' en 'Churn':
Churn
No     5174
Yes    1869
NC      224
Name: count, dtype: Int64

Chequando vacios en  'Churn' despues de reemplazar:
0

Chequeando nulos en 'Churn' despues de reemplazar:
0

In [32]:
#Crear columna cuentas diarias
df_normalizado['Cuentas_Diarias'] = df_normalizado['account.Charges.Monthly'] / 30
df_normalizado.head()

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.796667

In [33]:
# modificar a valores booleanos
for col in ['customer.Partner', 'customer.Dependents', 'phone.PhoneService', 'account.PaperlessBilling','customer.SeniorCitizen']:
    df_normalizado[col] = df_normalizado[col].replace({'Yes': 1, 'No': 0}).astype(bool)

/tmp/ipython-input-2932433011.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_normalizado[col] = df_normalizado[col].replace({'Yes': 1, 'No': 0}).astype(bool)
/tmp/ipython-input-2932433011.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_normalizado[col] = df_normalizado[col].replace({'Yes': 1, 'No': 0}).astype(bool)
/tmp/ipython-input-2932433011.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_normalizado[col] = df_normalizado[col].replace({'Yes': 1, 'No': 0}).astype(bool)
/tmp/ipython-input-2932433011.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_normalizado[col] = df_normalizado[col].replace({'Yes': 1, 'No': 0}).astype(bool)

In [34]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   string
 1   Churn                      7267 non-null   string
 2   customer.gender            7267 non-null   string
 3   customer.SeniorCitizen     7267 non-null   bool
 4   customer.Partner           7267 non-null   bool
 5   customer.Dependents        7267 non-null   bool
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   bool
 8   phone.MultipleLines        7267 non-null   string
 9   internet.InternetService   7267 non-null   string
 10  internet.OnlineSecurity    7267 non-null   string
 11  internet.OnlineBackup      7267 non-null   string
 12  internet.DeviceProtection  7267 non-null   string
 13  internet.TechSupport       7267 non-null   string
 14  internet.StreamingTV       7267 non-null   string
 15  internet.StreamingMovies   7267 non-null   string
 16  account.Contract           7267 non-null   string
 17  account.PaperlessBilling   7267 non-null   bool
 18  account.PaymentMethod      7267 non-null   string
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   float64
 21  Cuentas_Diarias            7267 non-null   float64
dtypes: bool(5), float64(3), int64(1), string(13)
memory usage: 1000.8 KB

##Análisis

In [38]:
#Evaluacion de datos generales del df
df_normalizado.describe()

,customer.tenure,account.Charges.Monthly,account.Charges.Total,Cuentas_Diarias
count,7267.000000,7267.000000,7267.000000,7267.000000
mean,32.346498,64.720098,2277.182035,2.157337
std,24.571773,30.129572,2268.648587,1.004319
min,0.000000,18.250000,0.000000,0.608333
25%,9.000000,35.425000,396.200000,1.180833
50%,29.000000,70.300000,1389.200000,2.343333
75%,55.000000,89.875000,3778.525000,2.995833
max,72.000000,118.750000,8684.800000,3.958333